spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChrisBafax/PizzaRestaurantProperties.git
          clone-on-start: true
          skip-ssl-validation: true
          force-pull: true
          # Using repository from GitHub.
          # Cloning the repository on start.
          # Skipping SSL validation.
          # Forcing pull.

server:
  port: 8888
  servlet:
    context-path: /config