spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        -

server:
  port: 8080
  # Use of port 8080 for the gateway service.

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka