spring:
  application:
    name: NOTIFICATION-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/config
  profiles:
    active: sms
  cloud:
    config:
      name: notification-service
# Import the properties from the ConfigService.