spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    # Uso del server H2 come file. In questo modo rimane sbloccato.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/RestaurantServiceDB;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    # Connettore del database.
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 0
  # Using a random port to avoid conflicts with other instances of the service.
  servlet:
    context-path: /api

app:
  pizza-service-url: http://localhost:9090/api/pizzas/restaurant
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Swagger UI
# http://localhost:9091/api/swagger-ui/index.html
# 192.168.1.160:9091/api/swagger-ui/index.html

# H2-Console
# http://localhost:9091/api/h2-console
# 192.168.1.160:9091/api/h2-console
# Inserire come db:
# jdbc:h2:file:~/data/RestaurantServiceDB
# Username e Password sono entrambe sa.


