spring:
  application:
    name: PIZZA-SERVICE
  config:
    import: optional:configserver:http://localhost:8888/config
  cloud:
    config:
      name: pizza-service
# Import the properties from the ConfigService.
# Forcing the name to look for in the ConfigService with the property spring.cloud.config.name.