spring:
  application:
    name: NOTIFICATION_SERVICE

app:
  rabbitmq:
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

server:
  port: 0
  # Using a random port to avoid conflicts with other instances of the service.

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
